package com.scottlogic.kafkapoc;
/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'smhall' at '22/09/16 16:06' with Gradle 2.13
 *
 * @author smhall, @date 22/09/16 16:06
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
