package com.scottlogic.kafkapoc;

import org.junit.Test;

import com.scottlogic.kafkapoc.Library;

import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'smhall' at '22/09/16 16:06' with Gradle 2.13
 *
 * @author smhall, @date 22/09/16 16:06
 */
public class LibraryTest {
	@Test
	public void testSomeLibraryMethod() {

		Library classUnderTest = new Library();
		assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
	}
}
